#!/usr/bin/env python3
"""
Script to check if all links in hyde-themes.json are accessible.
Exits with status 0 if all links are OK, 1 if broken links found.
Outputs broken links info to GitHub Actions output and issue_body.md
"""

import json
import sys
import os
import urllib.request
import urllib.error
import socket

# Timeout for each request in seconds
TIMEOUT = 10

# File paths
JSON_FILE = "hyde-themes.json"
ISSUE_BODY_FILE = "issue_body.md"


def check_link(url: str) -> tuple[bool, str]:
    """
    Check if a URL is accessible.
    Returns (is_accessible, error_message)
    """
    try:
        # Create a request with a User-Agent header
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "HyDE-Gallery-LinkChecker/1.0 (GitHub Actions)"
            },
        )

        # Try to open the URL with a timeout
        with urllib.request.urlopen(req, timeout=TIMEOUT) as response:
            # Consider 2xx and 3xx status codes as accessible
            if 200 <= response.status < 400:
                return True, ""
            else:
                return False, f"HTTP {response.status}"

    except urllib.error.HTTPError as e:
        return False, f"HTTP {e.code}"
    except urllib.error.URLError as e:
        return False, f"URL Error: {e.reason}"
    except socket.timeout:
        return False, "Timeout"
    except Exception as e:
        return False, f"Error: {str(e)}"


def main():
    # Load the JSON file
    try:
        with open(JSON_FILE, "r", encoding="utf-8") as f:
            themes = json.load(f)
    except FileNotFoundError:
        print(f"❌ Error: {JSON_FILE} not found")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Error: Invalid JSON in {JSON_FILE}: {e}")
        sys.exit(1)

    # Check each theme's LINK
    broken_links = []
    total_links = 0

    for theme in themes:
        theme_name = theme.get("THEME", "Unknown")
        link = theme.get("LINK", "")
        owner = theme.get("OWNER", "")

        if not link:
            continue

        total_links += 1
        is_accessible, error = check_link(link)

        if not is_accessible:
            broken_links.append({
                "theme": theme_name,
                "link": link,
                "owner": owner,
                "error": error,
            })
            print(f"❌ Broken: {theme_name} - {link} ({error})")
        else:
            print(f"✅ OK: {theme_name} - {link}")

    # Write GitHub Actions output
    has_broken = "true" if broken_links else "false"
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"has_broken_links={has_broken}\n")

    # Generate issue body if there are broken links
    if broken_links:
        with open(ISSUE_BODY_FILE, "w", encoding="utf-8") as f:
            f.write(f"# Broken Links Detected in hyde-themes.json\n\n")
            f.write(f"**Total links checked:** {total_links}\n")
            f.write(f"**Broken links found:** {len(broken_links)}\n\n")
            f.write(f"> This issue was automatically generated by the "
                    f"[Check Broken Links workflow](https://github.com/{os.environ.get('GITHUB_REPOSITORY', 'HyDE-Project/hyde-gallery')}/actions/runs/{os.environ.get('GITHUB_RUN_ID', 'N/A')})\n\n")
            f.write("## Broken Links\n\n")
            f.write("| Theme | Link | Error |\n")
            f.write("| --- | --- | --- |\n")

            for item in broken_links:
                f.write(f"| {item['theme']} | [{item['link']}]({item['link']}) | {item['error']} |\n")

            f.write("\n## Suggested Actions\n\n")
            f.write("1. Verify if the link is still valid\n")
            f.write("2. If the repository has been moved or deleted, update the LINK field in `hyde-themes.json`\n")
            f.write("3. If the owner has changed, update the OWNER field\n")
            f.write("4. Remove the entry if the theme is no longer available\n\n")
            f.write("---\n")
            from datetime import datetime, timezone
            f.write(f"*Generated on: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}*\n")

        print(f"\n📝 Issue body written to {ISSUE_BODY_FILE}")
        print(f"\n❌ Found {len(broken_links)} broken link(s) out of {total_links} total links")

        # Exit with error code to indicate broken links found
        sys.exit(1)
    else:
        print(f"\n✅ All {total_links} links are accessible!")
        sys.exit(0)


if __name__ == "__main__":
    main()
