name: Update README

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Use the latest Python version

      - name: Run Python script to update README
        run: |
          python generate_readme.py

      - name: Commit changes if any
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          if git diff-index --cached --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update README with new data"
          fi

      # Debug step removed - using built-in token with proper permissions

      - name: Push changes to remote repository
        # Only push changes on push events to master, not on pull requests
        if: github.event_name == 'push' && success()
        run: |
          # Using the built-in GITHUB_TOKEN with updated permissions
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
